### ISSUE TITLE
running problems

### ISSUE THREAD

**Issue by johannnnnnn** [jehiah/json2csv#27]
Hi!!

I've installed json2csv by 

$go get github.com/jehiah/json2csv

but when I try to do

$cat someFile.json | json2csv -k time,tx_index > output.csv

then I get the following:

2015/04/28 17:18:20 ERROR Decoding JSON at line 1: unexpected end of JSON input
{
2015/04/28 17:18:20 ERROR Decoding JSON at line 2: invalid character ':' after top-level value
  "time": 1348310820,
2015/04/28 17:18:20 ERROR Decoding JSON at line 3: invalid character ':' after top-level value
  "tx_index": 9741630
2015/04/28 17:18:20 ERROR Decoding JSON at line 4: invalid character '}' looking for beginning of value
}

and so on... What am I missing?

Thank you for you time.

**Comment by thinkjson** [comment]
json2csv expects one object per line.

**Comment by ladyrassilon** [comment]
Can you supply an example?

**Comment by Ssalasromero** [comment]
@thinkjson I got the same problem. What can I do to easily get an json output in one object per line? I usually format it with pretty print through python json.tools. 

Thx in advance
